tionTypes.js
// Restaurant
const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST";
const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
const CREATE_RESTAURANT_FAILURE = "CREATE_RESTAURANT_FAILURE";

const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST";
const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
const GET_ALL_RESTAURANTS_FAILURE = "GET_ALL_RESTAURANTS_FAILURE";

const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST";
const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
const DELETE_RESTAURANT_FAILURE = "DELETE_RESTAURANT_FAILURE";

const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST";
const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
const UPDATE_RESTAURANT_FAILURE = "UPDATE_RESTAURANT_FAILURE";

const GET_RESTAURANTS_BY_ID_REQUEST = "GET_RESTAURANTS_BY_ID_REQUEST";
const GET_RESTAURANTS_BY_ID_SUCCESS = "GET_RESTAURANTS_BY_ID_SUCCESS";
const GET_RESTAURANTS_BY_ID_FAILURE = "GET_RESTAURANTS_BY_ID_FAILURE";

const GET_RESTAURANTS_BY_USER_ID_REQUEST = "GET_RESTAURANTS_BY_USER_ID_REQUEST";
const GET_RESTAURANTS_BY_USER_ID_SUCCESS = "GET_RESTAURANTS_BY_USER_ID_SUCCESS";
const GET_RESTAURANTS_BY_USER_ID_FAILURE = "GET_RESTAURANTS_BY_USER_ID_FAILURE";

const UPDATE_RESTAURANTS_STATUS_REQUEST = "UPDATE_RESTAURANTS_STATUS_REQUEST";
const UPDATE_RESTAURANTS_STATUS_SUCCESS = "UPDATE_RESTAURANTS_STATUS_SUCCESS";
const UPDATE_RESTAURANTS_STATUS_FAILURE = "UPDATE_RESTAURANTS_STATUS_FAILURE";

// Event
const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

const GET_RESTAURANTS_EVENTS_REQUEST = "GET_RESTAURANTS_EVENTS_REQUEST";
const GET_RESTAURANTS_EVENTS_SUCCESS = "GET_RESTAURANTS_EVENTS_SUCCESS";
const GET_RESTAURANTS_EVENTS_FAILURE = "GET_RESTAURANTS_EVENTS_FAILURE";

// Event
const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

const GET_RESTAURANTS_CATEGORY_REQUEST = "GET_RESTAURANTS_CATEGORY_REQUEST";
const GET_RESTAURANTS_CATEGORY_SUCCESS = "GET_RESTAURANTS_CATEGORY_SUCCESS";
const GET_RESTAURANTS_CATEGORY_FAILURE = "GET_RESTAURANTS_CATEGORY_FAILURE";